name: First Workflow
# Manual trigger workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Multiple commands
        run: |
          echo "First output"
          echo "Second output"
